"""The "carved" ornament language (D-022): dark hand-carved wood with iron fittings, the
direction of Diego's hp-bars-new reference, standardised so every piece matches.

  containers ("planks": vital bars, hotbar beam, minimap ring, crest, banner, cards, plates):
      wood gradient body, outer dark rim EDGE, bevel lit from the top-left, sunken opening
  cells ("sunken": item slots, status tiles, wind disk):
      darker body with the bevel reversed, as if cut into the wood
  motifs: engraved rune (the V of the Valheim logo), iron rivet, diamond pommel / engraving
  grain: a wood-grain pass after rasterising (grain() below), vertical or horizontal
"""
import math

import numpy as np
from PIL import Image

WOOD_TOP = "#43352A"
WOOD_BOTTOM = "#1F1813"
EDGE = "#0B0908"
LIGHT = "#B89A7C"
SHADE = "#130E0B"
OPENING = "#080706"
GROOVE = "#110C09"
IRON_LIGHT = "#CFC3AE"
IRON_DARK = "#403933"

RIM = 2.2
BEVEL = 1.1
OPENING_RIM = 1.3

DEFS = (
    '<defs>'
    f'<linearGradient id="wood" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="{WOOD_TOP}"/><stop offset="1" stop-color="{WOOD_BOTTOM}"/></linearGradient>'
    f'<linearGradient id="lit" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{LIGHT}" stop-opacity="0.9"/>'
    f'<stop offset="0.55" stop-color="{LIGHT}" stop-opacity="0.15"/><stop offset="1" stop-color="{SHADE}" stop-opacity="0.9"/></linearGradient>'
    f'<linearGradient id="cut" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{SHADE}" stop-opacity="0.95"/>'
    f'<stop offset="0.5" stop-color="{SHADE}" stop-opacity="0.3"/><stop offset="1" stop-color="{LIGHT}" stop-opacity="0.75"/></linearGradient>'
    f'<radialGradient id="iron" cx="0.35" cy="0.35" r="0.75"><stop offset="0" stop-color="{IRON_LIGHT}"/><stop offset="1" stop-color="{IRON_DARK}"/></radialGradient>'
    '</defs>'
)


def svg(width, height, body, comment):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">\n'
            f'  <!-- {comment} Generated by tools/art/carved_shapes.py from tools/art/carved_style.py. Original work. -->\n'
            f'  {DEFS}\n{body}\n</svg>\n')


def plank(path):
    """A carved container body: wood fill, dark rim, bevel lit from the top-left."""
    return (f'  <path d="{path}" fill="url(#wood)" stroke="{EDGE}" stroke-width="{RIM}" stroke-linejoin="round"/>\n'
            f'  <path d="{path}" fill="none" stroke="url(#lit)" stroke-width="{BEVEL}" stroke-linejoin="round" transform="translate(0.5 0.5)" />\n')


def opening(path):
    """The hole a container shows its contents through: near-black, rim cut into the wood."""
    return (f'  <path d="{path}" fill="{OPENING}" fill-opacity="0.94" stroke="url(#cut)" stroke-width="{OPENING_RIM}" stroke-linejoin="round"/>\n')


def sunken(path, fill_opacity=0.92):
    """A carved cell: darker wood, bevel reversed."""
    return (f'  <path d="{path}" fill="#1B1511" fill-opacity="{fill_opacity}" stroke="{EDGE}" stroke-width="{RIM - 0.6}" stroke-linejoin="round"/>\n'
            f'  <path d="{path}" fill="none" stroke="url(#cut)" stroke-width="{BEVEL}" stroke-linejoin="round" transform="translate(0.4 0.4)"/>\n')


def chamfer(x, y, w, h, c):
    """Rectangle with cut corners (the carved look)."""
    return (f"M{x + c},{y} L{x + w - c},{y} L{x + w},{y + c} L{x + w},{y + h - c} L{x + w - c},{y + h} "
            f"L{x + c},{y + h} L{x},{y + h - c} L{x},{y + c} Z")


def rivet(cx, cy, r=1.9):
    return f'  <circle cx="{cx}" cy="{cy}" r="{r}" fill="url(#iron)" stroke="{EDGE}" stroke-width="0.7"/>\n'


def engrave(path):
    """An engraving: a dark groove with a thin lit lower-right lip."""
    return (f'  <path d="{path}" fill="{LIGHT}" fill-opacity="0.35" transform="translate(0.6 0.6)"/>\n'
            f'  <path d="{path}" fill="{GROOVE}"/>\n')


def rune_v(cx, cy, h):
    """The V of the Valheim logo as an engraved rune: two strokes meeting low, with serifs."""
    w = h * 0.78
    t = h * 0.2
    top = cy - h / 2
    bottom = cy + h / 2
    path = (f"M{cx - w / 2},{top} L{cx - w / 2 + t * 1.25},{top} L{cx},{bottom - t * 1.6} L{cx + w / 2 - t * 1.25},{top} "
            f"L{cx + w / 2},{top} L{cx + t * 0.55},{bottom} L{cx - t * 0.55},{bottom} Z")
    serif = f"M{cx - w / 2 - t * 0.3},{top} L{cx - w / 2 + t * 1.55},{top} L{cx - w / 2 + t * 1.35},{top + t * 0.45} L{cx - w / 2 - t * 0.1},{top + t * 0.45} Z"
    serif2 = f"M{cx + w / 2 + t * 0.3},{top} L{cx + w / 2 - t * 1.55},{top} L{cx + w / 2 - t * 1.35},{top + t * 0.45} L{cx + w / 2 + t * 0.1},{top + t * 0.45} Z"
    return engrave(path) + engrave(serif) + engrave(serif2)


def diamond(cx, cy, r):
    return engrave(f"M{cx},{cy - r} L{cx + r},{cy} L{cx},{cy + r} L{cx - r},{cy} Z")


def grain(image, vertical, strength=0.26, seed=5):
    """Wood grain: multiplies the lit pixels by long, slightly wavy streaks along the grain."""
    a = np.asarray(image.convert("RGBA")).astype(np.float32)
    h, w = a.shape[:2]
    rng = np.random.default_rng(seed)
    along, across = (h, w) if vertical else (w, h)
    t = np.linspace(0, 1, along)[:, None]
    u = np.arange(across)[None, :].astype(np.float32)
    wobble = 2.2 * np.sin(2 * math.pi * (t * 1.3 + rng.random())) + 1.1 * np.sin(2 * math.pi * (t * 3.7 + rng.random()))
    streak = np.zeros((along, across), np.float32)
    for f, amp in ((0.21, 1.0), (0.53, 0.55), (1.37, 0.3)):
        streak += amp * np.sin((u + wobble) * f + rng.random() * 6.28)
    streak += 0.35 * rng.standard_normal((along, across)).astype(np.float32)
    streak = (streak - streak.min()) / max(1e-6, streak.max() - streak.min())
    factor = 1.0 - strength / 2 + strength * streak
    if not vertical:
        factor = factor.T
    lum = a[..., :3].mean(axis=2, keepdims=True)
    mask = np.clip((lum - 12) / 40, 0, 1)            # leave near-black openings untouched
    a[..., :3] = a[..., :3] * (1 - mask + mask * factor[..., None])
    return Image.fromarray(np.clip(a, 0, 255).astype(np.uint8), "RGBA")
