"""The "carved" ornament language (D-022): dark hand-carved wood with iron fittings, the
direction of Diego's hp-bars-new reference, standardised so every piece matches.

  containers ("planks": vital bars, hotbar beam, minimap ring, crest, banner, cards, plates):
      wood gradient body, outer dark rim EDGE, bevel lit from the top-left, sunken opening
  cells ("sunken": item slots, status tiles, wind disk):
      darker body with the bevel reversed, as if cut into the wood
  motifs: engraved rune (the V of the Valheim logo), iron rivet, diamond pommel / engraving
  grain: a wood-grain pass after rasterising (grain() below), vertical or horizontal
"""
import math

import numpy as np
from PIL import Image

# R-040 comparison: the reference reads as worn, dark weathered wood with bright, chipped edges;
# the first palette was so dark that rails and openings merged into one black mass.
WOOD_TOP = "#57493D"
WOOD_BOTTOM = "#2C241E"
EDGE = "#0A0807"
LIGHT = "#D4B38D"
INLAY = "#BC9C77"
SHADE = "#130E0B"
OPENING = "#16110E"
GROOVE = "#110C09"
IRON_LIGHT = "#CFC3AE"
IRON_DARK = "#403933"

RIM = 2.2
BEVEL = 1.5
OPENING_RIM = 1.7

DEFS = (
    '<defs>'
    f'<linearGradient id="wood" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="{WOOD_TOP}"/><stop offset="1" stop-color="{WOOD_BOTTOM}"/></linearGradient>'
    f'<linearGradient id="lit" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{LIGHT}" stop-opacity="0.9"/>'
    f'<stop offset="0.55" stop-color="{LIGHT}" stop-opacity="0.15"/><stop offset="1" stop-color="{SHADE}" stop-opacity="0.9"/></linearGradient>'
    f'<linearGradient id="cut" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{SHADE}" stop-opacity="0.95"/>'
    f'<stop offset="0.5" stop-color="{SHADE}" stop-opacity="0.3"/><stop offset="1" stop-color="{LIGHT}" stop-opacity="0.75"/></linearGradient>'
    f'<radialGradient id="iron" cx="0.35" cy="0.35" r="0.75"><stop offset="0" stop-color="{IRON_LIGHT}"/><stop offset="1" stop-color="{IRON_DARK}"/></radialGradient>'
    '</defs>'
)


def svg(width, height, body, comment):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">\n'
            f'  <!-- {comment} Generated by tools/art/carved_shapes.py from tools/art/carved_style.py. Original work. -->\n'
            f'  {DEFS}\n{body}\n</svg>\n')


def plank(path):
    """A carved container body: wood fill, dark rim, a worn light edge all round and a stronger
    bevel lit from the top-left."""
    return (f'  <path d="{path}" fill="url(#wood)" stroke="{EDGE}" stroke-width="{RIM}" stroke-linejoin="round"/>\n'
            f'  <path d="{path}" fill="none" stroke="{LIGHT}" stroke-opacity="0.45" stroke-width="0.9" stroke-linejoin="round" transform="translate(0.35 0.35)"/>\n'
            f'  <path d="{path}" fill="none" stroke="url(#lit)" stroke-width="{BEVEL}" stroke-linejoin="round" transform="translate(0.5 0.5)" />\n')


def inlay(path):
    """A raised light motif (rune, diamond) set into a sunken panel: light metal-like fill with
    a dark drop to the lower right, so it reads at HUD size."""
    return (f'  <path d="{path}" fill="{EDGE}" fill-opacity="0.8" transform="translate(0.7 0.7)"/>\n'
            f'  <path d="{path}" fill="{INLAY}"/>\n')


def opening(path):
    """The hole a container shows its contents through: near-black, rim cut into the wood."""
    return (f'  <path d="{path}" fill="{OPENING}" fill-opacity="0.94" stroke="url(#cut)" stroke-width="{OPENING_RIM}" stroke-linejoin="round"/>\n')


def sunken(path, fill_opacity=0.92):
    """A carved cell: darker wood, bevel reversed."""
    return (f'  <path d="{path}" fill="#1B1511" fill-opacity="{fill_opacity}" stroke="{EDGE}" stroke-width="{RIM - 0.6}" stroke-linejoin="round"/>\n'
            f'  <path d="{path}" fill="none" stroke="url(#cut)" stroke-width="{BEVEL}" stroke-linejoin="round" transform="translate(0.4 0.4)"/>\n')


def chamfer(x, y, w, h, c):
    """Rectangle with cut corners (the carved look)."""
    return (f"M{x + c},{y} L{x + w - c},{y} L{x + w},{y + c} L{x + w},{y + h - c} L{x + w - c},{y + h} "
            f"L{x + c},{y + h} L{x},{y + h - c} L{x},{y + c} Z")


def rivet(cx, cy, r=1.9):
    return f'  <circle cx="{cx}" cy="{cy}" r="{r}" fill="url(#iron)" stroke="{EDGE}" stroke-width="0.7"/>\n'


def engrave(path):
    """An engraving: a dark groove with a thin lit lower-right lip."""
    return (f'  <path d="{path}" fill="{LIGHT}" fill-opacity="0.35" transform="translate(0.6 0.6)"/>\n'
            f'  <path d="{path}" fill="{GROOVE}"/>\n')


def rune_v(cx, cy, h, mark=None):
    """The V of the Valheim logo as a rune: two strokes meeting low, with serifs. `mark` is
    engrave (a dark groove) or inlay (a light raised rune, the default for panels)."""
    mark = mark or engrave
    w = h * 0.78
    t = h * 0.2
    top = cy - h / 2
    bottom = cy + h / 2
    path = (f"M{cx - w / 2},{top} L{cx - w / 2 + t * 1.25},{top} L{cx},{bottom - t * 1.6} L{cx + w / 2 - t * 1.25},{top} "
            f"L{cx + w / 2},{top} L{cx + t * 0.55},{bottom} L{cx - t * 0.55},{bottom} Z")
    serif = f"M{cx - w / 2 - t * 0.3},{top} L{cx - w / 2 + t * 1.55},{top} L{cx - w / 2 + t * 1.35},{top + t * 0.45} L{cx - w / 2 - t * 0.1},{top + t * 0.45} Z"
    serif2 = f"M{cx + w / 2 + t * 0.3},{top} L{cx + w / 2 - t * 1.55},{top} L{cx + w / 2 - t * 1.35},{top + t * 0.45} L{cx + w / 2 + t * 0.1},{top + t * 0.45} Z"
    return mark(path) + mark(serif) + mark(serif2)


def diamond(cx, cy, r, mark=None):
    return (mark or engrave)(f"M{cx},{cy - r} L{cx + r},{cy} L{cx},{cy + r} L{cx - r},{cy} Z")


def _blotches(h, w, rng):
    """Soft 0..1 blotches at two scales plus sparse bright chips."""
    out = np.zeros((h, w), np.float32)
    for cells, amp in ((6, 0.6), (18, 0.4)):
        small = rng.random((cells * h // max(h, w) + 2, cells * w // max(h, w) + 2)).astype(np.float32)
        img = Image.fromarray((small * 255).astype(np.uint8)).resize((w, h), Image.BICUBIC)
        out += amp * np.asarray(img, np.float32) / 255
    chips = (rng.random((h, w)) > 0.985).astype(np.float32) * 0.6
    return np.clip(out + chips, 0, 1.4)


def grain(image, vertical, strength=0.34, seed=5):
    """Wood grain: multiplies the lit pixels by long, slightly wavy streaks along the grain."""
    a = np.asarray(image.convert("RGBA")).astype(np.float32)
    h, w = a.shape[:2]
    rng = np.random.default_rng(seed)
    along, across = (h, w) if vertical else (w, h)
    t = np.linspace(0, 1, along)[:, None]
    u = np.arange(across)[None, :].astype(np.float32)
    wobble = 2.2 * np.sin(2 * math.pi * (t * 1.3 + rng.random())) + 1.1 * np.sin(2 * math.pi * (t * 3.7 + rng.random()))
    streak = np.zeros((along, across), np.float32)
    for f, amp in ((0.21, 1.0), (0.53, 0.55), (1.37, 0.3)):
        streak += amp * np.sin((u + wobble) * f + rng.random() * 6.28)
    streak += 0.35 * rng.standard_normal((along, across)).astype(np.float32)
    streak = (streak - streak.min()) / max(1e-6, streak.max() - streak.min())
    factor = 1.0 - strength / 2 + strength * streak
    if not vertical:
        factor = factor.T
    # Wear: blotchy weathering and small chips, so the surface reads as old, handled wood
    # rather than smooth plastic (R-040 comparison).
    blot = _blotches(h, w, rng)
    factor = factor * (0.84 + 0.3 * blot)
    lum = a[..., :3].mean(axis=2, keepdims=True)
    mask = np.clip((lum - 12) / 40, 0, 1)            # leave near-black openings untouched
    a[..., :3] = a[..., :3] * (1 - mask + mask * factor[..., None])
    return Image.fromarray(np.clip(a, 0, 255).astype(np.uint8), "RGBA")
