"""The GenesisUI ornament language, in one place (docs/ART-DIRECTION.md §4a).

Every UI shape is generated from these constants and motifs so the pieces read as one
family (R-030: "each piece is beautiful alone, but they do not fit together"):

  containers (bars, hotbar plate, minimap ring, crest, banner, medallion):
      gold outer line CONTAINER_OUTER, bronze inner line INNER at INSET
  cells (item slots, status tiles, small disks):
      bronze outer line CELL_OUTER, faint gold hairline HAIRLINE inside
  motifs: diamond (finials, cardinal points), volute (terminal ends), bead (tips, joints)
  fill: FILL at FILL_OPACITY everywhere
"""

GOLD_TOP = "#F7E283"
GOLD_BOTTOM = "#B8863E"
BRONZE = "#705B3F"
FILL = "#0B0D0C"
FILL_OPACITY = 0.9

CONTAINER_OUTER = 1.6
INNER = 0.9
INSET = 3.2
CELL_OUTER = 1.4
HAIRLINE = 0.8
HAIRLINE_OPACITY = 0.2
MOTIF_STROKE = 1.1

DEFS = (f'<defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1">'
        f'<stop offset="0" stop-color="{GOLD_TOP}"/><stop offset="1" stop-color="{GOLD_BOTTOM}"/>'
        f'</linearGradient></defs>')


def svg(width, height, body, comment):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">\n'
            f'  <!-- {comment} Generated by tools/art/shapes.py from tools/art/style.py. Original work. -->\n'
            f'  {DEFS}\n{body}\n</svg>\n')


def container(path, inner_path):
    return (f'  <path d="{path}" fill="{FILL}" fill-opacity="{FILL_OPACITY}" stroke="url(#g)" '
            f'stroke-width="{CONTAINER_OUTER}" stroke-linejoin="round"/>\n'
            f'  <path d="{inner_path}" fill="none" stroke="{BRONZE}" stroke-width="{INNER}" stroke-linejoin="round"/>\n')


def cell_rect(x, y, w, h, r):
    return (f'  <rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}" fill="{FILL}" fill-opacity="{FILL_OPACITY}" '
            f'stroke="{BRONZE}" stroke-width="{CELL_OUTER}"/>\n'
            f'  <rect x="{x + 2.6}" y="{y + 2.6}" width="{w - 5.2}" height="{h - 5.2}" rx="{max(0.5, r - 1.6)}" fill="none" '
            f'stroke="{GOLD_TOP}" stroke-opacity="{HAIRLINE_OPACITY}" stroke-width="{HAIRLINE}"/>\n')


def diamond(cx, cy, r, hollow=False):
    out = f'  <path d="M{cx},{cy - r} l{r},{r} -{r},{r} -{r},-{r}z" fill="url(#g)"/>\n'
    if hollow:
        h = r * 0.42
        out += f'  <path d="M{cx},{cy - h} l{h},{h} -{h},{h} -{h},-{h}z" fill="{FILL}"/>\n'
    return out


def bead(cx, cy, r=1.4):
    return f'  <circle cx="{cx}" cy="{cy}" r="{r}" fill="url(#g)"/>\n'


def volute(x, y, direction, size=1.0, downward=False):
    """A small curl starting at (x, y), rolling outward (direction -1 = left, +1 = right),
    upward by default or downward."""
    d, s, v = direction, size, (1 if downward else -1)
    return (f'  <path d="M{x},{y} C{x + d * 3.4 * s},{y + v * 0.8 * s} {x + d * 4.8 * s},{y + v * 4.4 * s} {x + d * 2.6 * s},{y + v * 6.2 * s} '
            f'C{x + d * 1.0 * s},{y + v * 7.4 * s} {x - d * 1.0 * s},{y + v * 6.0 * s} {x - d * 0.2 * s},{y + v * 4.2 * s}" '
            f'fill="none" stroke="url(#g)" stroke-width="{MOTIF_STROKE}" stroke-linecap="round"/>\n')
